/**
 * Cloud Run worker: Download PGP 23andMe genetic files and detect genome build.
 *
 * PARTICIPANT_SOURCE controls where the participant list comes from:
 *   PARTICIPANT_SOURCE=fetch     (default) -> calls fetch23andMeParticipants()
 *                                              fresh, saves the raw list, then
 *                                              downloads every participant's file.
 *   PARTICIPANT_SOURCE=existing            -> skips fetching; loads a participant
 *                                              list already sitting in the bucket
 *                                              (path controlled by
 *                                              INPUT_PARTICIPANT_JSON) and
 *                                              re-downloads/re-processes those.
 *
 * Workflow after the participant list is obtained (same either way):
 * For each participant whose filenameExtension is "txt" or "zip":
 *    load23andMeFileCloud_unknwn(downloadUrl, id) downloads the file and:
 *      - for .zip:  extracts the inner .txt (loaded.filename = inner name,
 *                   loaded.innerFilename = inner name)
 *      - for .txt:  returns the TXT as-is
 *    and scans the first 128 KB of the TXT header to attach:
 *      loaded.genomeBuild              -> "36" | "37" | "38" | null
 *      loaded.matchedLineGenomeBuild   -> the header line that produced the match
 *      loaded.valid23File              -> true if "This data file generated by 23andMe" appears
 *      loaded.matchedLineValid23File   -> that signature line, or null
 *    Recognized build markers: "build 36/37/38", "GRCh36/37/38", "hg18/19/38".
 *
 * On failure, the SDK attaches structured fields to the thrown error:
 *   err.status        -> HTTP status (e.g. 401)
 *   err.requestedUrl  -> URL you asked for
 *   err.finalUrl      -> URL after redirects (e.g. the arvadosapi.com collection URL)
 *   err.source        -> "direct" or "directory"
 * These get recorded on the participant record and 401s are broken out into
 * their own report file.
 *
 * Outputs:
 *   participantList/participants_${LIMIT}.json                  (only when fetching fresh)
 *   updatedParticipantsList/participants_${LIMIT}_with_build_${dateStamp}.json
 *   runReports/unauthorized_401s_${LIMIT}_${dateStamp}.json
 *   runReports/import_report_${LIMIT}_${dateStamp}.json
 */


// shell commands:
// gcloud builds submit \
  // --tag gcr.io/personalgenomes/all23_job .

// gcloud run jobs create all23_job \
//   --image gcr.io/personalgenomes/all23_job \
//   --region us-east4 \
//   --memory 32Gi \
//   --cpu 8 \
//   --task-timeout 14400 \
//   --max-retries 0 \
//   --command=node \
//   --args=--expose-gc,--max-old-space-size=28672,indexFull2.js \
//   --set-env-vars BUCKET_NAME=all23_07072026,LIMIT=1017,BATCH_SIZE=10,PARTICIPANT_SOURCE=fetch

// To re-run against an existing participant list instead:
//   --set-env-vars BUCKET_NAME=all23_07072026,LIMIT=1017,PARTICIPANT_SOURCE=existing,INPUT_PARTICIPANT_JSON=participantList/participants_1017.json

// gcloud run jobs execute all23_job \
//   --region us-east4

import { Storage } from "@google-cloud/storage";

import {
  fetch23andMeParticipants,
  load23andMeFileCloud_unknwn
} from "personal_genomes_project_sdk/cloud_sdk.mjs";

const storage = new Storage();

function getDateStamp() {
  const now = new Date();
  const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(now.getUTCDate()).padStart(2, "0");
  const yyyy = now.getUTCFullYear();
  const hh = String(now.getUTCHours()).padStart(2, "0");
  const min = String(now.getUTCMinutes()).padStart(2, "0");
  return `${mm}${dd}${yyyy}_${hh}${min}`;
}

// Only use BUCKET_NAME env var if explicitly set; otherwise build one
// from today's date, e.g. all23_07072026_1432
const BUCKET_NAME = process.env.BUCKET_NAME || `all23_${getDateStamp()}`;

const LIMIT = Number(process.env.LIMIT || 6);
const BATCH_SIZE = Number(process.env.BATCH_SIZE || 10);

// "fetch" (default) = pull a fresh participant list from the PGP site.
// "existing"        = reuse a participant list already saved in the bucket.
const PARTICIPANT_SOURCE = String(
  process.env.PARTICIPANT_SOURCE || "fetch"
).toLowerCase();

if (!["fetch", "existing"].includes(PARTICIPANT_SOURCE)) {
  throw new Error(
    `Invalid PARTICIPANT_SOURCE="${PARTICIPANT_SOURCE}". Must be "fetch" or "existing".`
  );
}

// Only used when PARTICIPANT_SOURCE=existing. Path to the participant list
// ALREADY in the bucket. Point this at either the raw list
// (participantList/participants_${LIMIT}.json) or a previous updated list
// (updatedParticipantsList/participants_${LIMIT}_with_build*.json) if you
// want to retry only the ones that failed/were skipped before.
const INPUT_PARTICIPANT_JSON =
  process.env.INPUT_PARTICIPANT_JSON ||
  `participantList/participants_${LIMIT}.json`;

async function ensureBucketExists(bucketName) {
  const bucket = storage.bucket(bucketName);

  const [exists] = await bucket.exists();

  if (exists) {
    console.log(`Bucket already exists: gs://${bucketName}`);
    return bucket;
  }

  console.log(`Creating bucket: gs://${bucketName}`);

  try {
    await storage.createBucket(bucketName, {
      location: "US-EAST4",       // match your Cloud Run job's region
      storageClass: "STANDARD"
    });

    console.log(`Bucket created: gs://${bucketName}`);
  } catch (err) {
    // Race condition guard: if two runs try to create it at the same
    // moment, GCS returns 409 for the loser — treat that as success.
    if (err.code === 409) {
      console.log(`Bucket already existed (race condition): gs://${bucketName}`);
    } else {
      throw err;
    }
  }

  return storage.bucket(bucketName);
}

function getDataToSave(loaded) {
  if (typeof loaded.txt === "string") {
    return loaded.txt;
  }

  if (Buffer.isBuffer(loaded.buffer)) {
    return loaded.buffer;
  }

  if (loaded.buffer instanceof ArrayBuffer) {
    return Buffer.from(loaded.buffer);
  }

  if (ArrayBuffer.isView(loaded.buffer)) {
    return Buffer.from(
      loaded.buffer.buffer,
      loaded.buffer.byteOffset,
      loaded.buffer.byteLength
    );
  }

  return null;
}

function getSizeMB(data) {
  const sizeBytes =
    typeof data === "string"
      ? Buffer.byteLength(data, "utf8")
      : data.length;

  return Number((sizeBytes / 1024 / 1024).toFixed(2));
}

function makeNullBuildParticipant(participant, reason) {
  return {
    ...participant,
    valid23File: false,
    matchedLineValid23File: null,
    genomeBuild: null,
    genomeBuildFiles: [],
    processingNote: reason
  };
}

// Extracts the numeric file id from a PGP download URL, e.g.
// https://my.pgp-hms.org/user_file/download/4177 -> "4177".
// This id is unique per uploaded file, so it disambiguates cases where the
// same participant has multiple files sharing the same inner filename.
function getDownloadId(downloadUrl) {
  const match = String(downloadUrl || "").match(/\/download\/(\d+)/);
  return match ? match[1] : null;
}

// Builds: <id>_<numericDownloadId>_<filename>
// The numericDownloadId guarantees uniqueness even when a participant uploads
// two or more files with identical inner filenames (which previously collided
// and silently overwrote each other in GCS).
function makeSavedFilename(id, filename, downloadUrl) {
  const downloadId = getDownloadId(downloadUrl);

  if (!filename) {
    return downloadId ? `${id}_${downloadId}_unknown.txt` : `${id}_unknown.txt`;
  }

  let safeFilename = filename.replace(/[\/\\?%*:|"<>]/g, "_");

  // Strip a leading "<id>_" the inner filename may already carry, so we don't
  // produce huBB5257_huBB5257_20110420205535.txt.
  if (safeFilename.toLowerCase().startsWith(`${id.toLowerCase()}_`)) {
    safeFilename = safeFilename.slice(id.length + 1);
  }

  // If we couldn't parse a download id, fall back to <id>_<filename>.
  if (!downloadId) {
    return `${id}_${safeFilename}`;
  }

  return `${id}_${downloadId}_${safeFilename}`;
}

async function loadParticipantsFromBucket(bucket, path) {
  const [contents] = await bucket.file(path).download();
  const participants = JSON.parse(contents.toString("utf8"));

  if (!Array.isArray(participants)) {
    throw new Error(`Expected an array in ${path}, got ${typeof participants}`);
  }

  return participants;
}

async function main() {
  const bucket = await ensureBucketExists(BUCKET_NAME);

  console.log("Starting genetic file import...");
  console.log({
    BUCKET_NAME,
    LIMIT,
    BATCH_SIZE,
    PARTICIPANT_SOURCE,
    INPUT_PARTICIPANT_JSON: PARTICIPANT_SOURCE === "existing" ? INPUT_PARTICIPANT_JSON : "(n/a - fetching fresh)"
  });

  let participants;
  let participantSourcePath;

  if (PARTICIPANT_SOURCE === "existing") {
    participants = await loadParticipantsFromBucket(bucket, INPUT_PARTICIPANT_JSON);
    participantSourcePath = INPUT_PARTICIPANT_JSON;

    console.log(
      `Loaded ${participants.length} participants from gs://${BUCKET_NAME}/${INPUT_PARTICIPANT_JSON}`
    );
  } else {
    participants = await fetch23andMeParticipants(LIMIT, {
      batchSize: BATCH_SIZE
    });

    console.log(`Participants found: ${participants.length}`);

    const participantOutputPath = `participantList/participants_${LIMIT}.json`;

    await bucket.file(participantOutputPath).save(
      JSON.stringify(participants, null, 2),
      { contentType: "application/json" }
    );

    console.log(
      `Saved raw participant JSON to gs://${BUCKET_NAME}/${participantOutputPath}`
    );

    participantSourcePath = participantOutputPath;
  }

  let savedCount = 0;
  let failedCount = 0;
  let skippedCount = 0;
  let unauthorizedCount = 0;

  const updatedParticipants = [];
  const unauthorizedFailures = [];

  for (const participant of participants) {
    try {
      if (!participant?.downloadUrl) {
        skippedCount++;

        console.warn(`Skipping ${participant?.id}: no downloadUrl`);

        updatedParticipants.push(
          makeNullBuildParticipant(participant, "no downloadUrl")
        );

        continue;
      }

      const allowedExtensions = ["txt", "zip"];
      const extension = String(participant.filenameExtension || "").toLowerCase();

      // Skip known non-TXT/ZIP files, but allow unknown/null URLs to be inspected.
      if (extension && !allowedExtensions.includes(extension)) {
        skippedCount++;

        console.warn(
          `Skipping ${participant.id}: unsupported filenameExtension=${participant.filenameExtension}`
        );

        updatedParticipants.push(
          makeNullBuildParticipant(
            participant,
            `unsupported filenameExtension=${participant.filenameExtension}`
          )
        );

        continue;
      }

      console.log(`Processing ${participant.id}`);
      console.log(`Download URL: ${participant.downloadUrl}`);
      console.log(`File extension from metadata: ${participant.filenameExtension}`);

      const loaded = await load23andMeFileCloud_unknwn(
        participant.downloadUrl,
        participant.id
      );

      const loadedExtension = String(
        loaded.filenameExtension || ""
      ).toLowerCase();

      // ZIP files should be extracted to TXT by the loader.
      // Therefore, the final loaded file should be txt.
      if (loadedExtension !== "txt") {
        skippedCount++;

        console.warn(
          `Skipping ${participant.id}: downloaded unsupported file=${loaded.filename}, extension=${loaded.filenameExtension}`
        );

        updatedParticipants.push(
          makeNullBuildParticipant(
            participant,
            `downloaded unsupported file=${loaded.filename}, extension=${loaded.filenameExtension}`
          )
        );

        continue;
      }

      const dataToSave = getDataToSave(loaded);

      if (!dataToSave) {
        throw new Error("Downloaded TXT is empty or unsupported");
      }

      if (typeof dataToSave === "string" && !dataToSave.trim()) {
        throw new Error("Downloaded TXT is empty");
      }

      if (Buffer.isBuffer(dataToSave) && dataToSave.length === 0) {
        throw new Error("Downloaded TXT buffer is empty");
      }

      // For ZIPs, loaded.filename is the extracted inner .txt name.
      // For direct .txt files, it's the original filename.
      // Save under <id>_<numericDownloadId>_<filename>
      const savedFilename = makeSavedFilename(
        participant.id,
        loaded.filename,
        participant.downloadUrl
      );

      const outputPath = `geneticFiles/${savedFilename}`;

      await bucket.file(outputPath).save(dataToSave, {
        contentType: "text/plain"
      });

      const sizeMB = getSizeMB(dataToSave);

      updatedParticipants.push({
        ...participant,
        innerFilename: loaded.innerFilename || participant.innerFilename || null,
        valid23File: loaded.valid23File,
        matchedLineValid23File: loaded.matchedLineValid23File,
        genomeBuild: loaded.genomeBuild,
        genomeBuildFiles: [
          {
            downloadUrl: participant.downloadUrl || null,
            filename: loaded.filename || null,
            gcsPath: outputPath,
            gcsfilename: savedFilename,
            sizeMB,
            matchedLine: loaded.matchedLineGenomeBuild
          }
        ]
      });

      savedCount++;

      console.log(`Saved ${savedCount}: gs://${BUCKET_NAME}/${outputPath}`);
      console.log({
        id: participant.id,
        genomeBuild: loaded.genomeBuild,
        matchedLine: loaded.matchedLineGenomeBuild
      });
    } catch (err) {
      failedCount++;

      // The SDK attaches these directly to the thrown error:
      //   err.status        -> HTTP status (e.g. 401)
      //   err.requestedUrl  -> URL you asked for
      //   err.finalUrl      -> URL after redirects (e.g. the arvadosapi.com collection URL)
      //   err.source        -> "direct" or "directory"
      const httpStatus = err.status ?? null;
      const finalUrlAtFailure = err.finalUrl || participant.finalUrl || null;
      const requestedUrl = err.requestedUrl || participant.downloadUrl || null;
      const failureSource = err.source || null;

      const isUnauthorized = httpStatus === 401;

      if (isUnauthorized) {
        unauthorizedCount++;
      }

      console.error(
        `FAILED ${participant?.id}: ${err.message}` +
        (httpStatus ? ` [status=${httpStatus}]` : "") +
        (failureSource ? ` [source=${failureSource}]` : "") +
        (finalUrlAtFailure ? ` [finalUrl=${finalUrlAtFailure}]` : "")
      );

      if (isUnauthorized) {
        unauthorizedFailures.push({
          id: participant.id,
          requestedUrl,
          finalUrl: finalUrlAtFailure,
          httpStatus,
          source: failureSource,
          errorMessage: err.message
        });
      }

      updatedParticipants.push({
        ...participant,
        valid23File: false,
        matchedLineValid23File: null,
        genomeBuild: null,
        genomeBuildFiles: [],
        httpStatusDownloadAttempt: httpStatus,
        finalUrlAtFailure,
        requestedUrlAtFailure: requestedUrl,
        failureSource,
        processingNote: `FAILED: ${err.message}`
      });
    }
  }

  const dateStamp = getDateStamp();

  const updatedParticipantOutputPath =
    `updatedParticipantsList/participants_${LIMIT}_with_build_${dateStamp}.json`;

  await bucket.file(updatedParticipantOutputPath).save(
    JSON.stringify(updatedParticipants, null, 2),
    { contentType: "application/json" }
  );

  console.log(
    `Saved updated participant JSON to gs://${BUCKET_NAME}/${updatedParticipantOutputPath}`
  );

  const unauthorizedOutputPath = `runReports/unauthorized_401s_${LIMIT}_${dateStamp}.json`;

  await bucket.file(unauthorizedOutputPath).save(
    JSON.stringify(unauthorizedFailures, null, 2),
    { contentType: "application/json" }
  );

  console.log(
    `Saved 401 failures (${unauthorizedFailures.length}) to gs://${BUCKET_NAME}/${unauthorizedOutputPath}`
  );

  const reportOutputPath = `runReports/import_report_${LIMIT}_${dateStamp}.json`;

  const report = {
    bucketName: BUCKET_NAME,
    dateStamp,
    participantSource: PARTICIPANT_SOURCE,
    participantSourcePath,
    totalParticipants: participants.length,
    saved: savedCount,
    failed: failedCount,
    skipped: skippedCount,
    unauthorized401s: unauthorizedCount,
    updatedParticipantJson: updatedParticipantOutputPath,
    unauthorizedFailuresJson: unauthorizedOutputPath
  };

  await bucket.file(reportOutputPath).save(
    JSON.stringify(report, null, 2),
    { contentType: "application/json" }
  );

  console.log(`Saved report to gs://${BUCKET_NAME}/${reportOutputPath}`);
  console.log("Run complete.");
  console.log(report);
}

main().catch(err => {
  console.error("FATAL ERROR:");
  console.error(err);
  process.exit(1);
});
