/**
 * Cloud Run worker: Download PGP 23andMe genetic files and detect genome build.
 *
 * Workflow (per LIMIT participants):
 * 1. fetch23andMeParticipants(LIMIT, { batchSize }) — parse the PGP 23andMe page,
 *    resolve each row's download URL/filename/extension. ZIPs are NOT peeked
 *    inside here; the inner TXT name comes from the SDK loader instead.
 *    Raw list is saved to: participantList/participants_${LIMIT}.json
 *
 * 2. For each participant whose filenameExtension is "txt" or "zip":
 *    load23andMeFileCloud_unknwn(downloadUrl, id) downloads the file and:
 *      - for .zip:  extracts the inner .txt (loaded.filename = inner name,
 *                   loaded.innerFilename = inner name)
 *      - for .txt:  returns the TXT as-is
 *    and scans the first 128 KB of the TXT header to attach:
 *      loaded.genomeBuild              -> "36" | "37" | "38" | null
 *      loaded.matchedLineGenomeBuild   -> the header line that produced the match
 *      loaded.valid23File              -> true if "This data file generated by 23andMe" appears
 *      loaded.matchedLineValid23File   -> that signature line, or null
 *    Recognized build markers: "build 36/37/38", "GRCh36/37/38", "hg18/19/38".
 *
 * 3. Save the TXT to: geneticFiles/<id>_<loaded.filename>
 *    (For ZIP sources this is the inner TXT name, so files always land as .txt.)
 *
 * 4. Append to updatedParticipants with: genomeBuild + genomeBuildFiles[] (gcsPath,
 *    gcsfilename, sizeMB, matchedLine). Saved to:
 *    updatedParticipantsList/participants_${LIMIT}_with_build.json
 *
 * 5. Save run report (saved/failed/skipped counts) to:
 *    runReports/import_report_${LIMIT}_${timestamp}.json
 */

import { Storage } from "@google-cloud/storage";

import {
  fetch23andMeParticipants,
  load23andMeFileCloud_unknwn
} from "personal_genomes_project_sdk/cloud_sdk.mjs";

const BUCKET_NAME = process.env.BUCKET_NAME || "all23_06252026";
const LIMIT = Number(process.env.LIMIT || 6);
const BATCH_SIZE = Number(process.env.BATCH_SIZE || 10);

const storage = new Storage();
const bucket = storage.bucket(BUCKET_NAME);



function getDataToSave(loaded) {
  if (typeof loaded.txt === "string") {
    return loaded.txt;
  }

  if (Buffer.isBuffer(loaded.buffer)) {
    return loaded.buffer;
  }

  if (loaded.buffer instanceof ArrayBuffer) {
    return Buffer.from(loaded.buffer);
  }

  if (ArrayBuffer.isView(loaded.buffer)) {
    return Buffer.from(
      loaded.buffer.buffer,
      loaded.buffer.byteOffset,
      loaded.buffer.byteLength
    );
  }

  return null;
}

function getSizeMB(data) {
  const sizeBytes =
    typeof data === "string"
      ? Buffer.byteLength(data, "utf8")
      : data.length;

  return Number((sizeBytes / 1024 / 1024).toFixed(2));
}

function makeNullBuildParticipant(participant, reason) {
  return {
    ...participant,
    valid23File: false,
    matchedLineValid23File: null,
    genomeBuild: null,
    genomeBuildFiles: [],
    processingNote: reason
  };
}

function makeSavedFilename(id, filename) {
  if (!filename) return `${id}_unknown.txt`;

  const safeFilename = filename.replace(/[\/\\?%*:|"<>]/g, "_");

  // Prevent huBB5257_huBB5257_20110420205535.txt
  if (safeFilename.toLowerCase().startsWith(`${id.toLowerCase()}_`)) {
    return safeFilename;
  }

  return `${id}_${safeFilename}`;
}

async function main() {
  console.log("Starting unknown-version genetic file import...");
  console.log({
    BUCKET_NAME,
    LIMIT,
    BATCH_SIZE
  });

  const participants = await fetch23andMeParticipants(LIMIT, {
    batchSize: BATCH_SIZE
  });

  console.log(`Participants found: ${participants.length}`);

  const participantOutputPath = `participantList/participants_${LIMIT}.json`;

  await bucket.file(participantOutputPath).save(
    JSON.stringify(participants, null, 2),
    {
      contentType: "application/json"
    }
  );

  console.log(
    `Saved raw participant JSON to gs://${BUCKET_NAME}/${participantOutputPath}`
  );

  let savedCount = 0;
  let failedCount = 0;
  let skippedCount = 0;

  const updatedParticipants = [];

  for (const participant of participants) {
    try {
      if (!participant?.downloadUrl) {
        skippedCount++;

        console.warn(`Skipping ${participant?.id}: no downloadUrl`);

        updatedParticipants.push(
          makeNullBuildParticipant(participant, "no downloadUrl")
        );

        continue;
      }

      const allowedExtensions = ["txt", "zip"];
      const extension = String(participant.filenameExtension || "").toLowerCase();

      // Skip known non-TXT/ZIP files, but allow unknown/null URLs to be inspected.
      if (extension && !allowedExtensions.includes(extension)) {
        skippedCount++;

        console.warn(
          `Skipping ${participant.id}: unsupported filenameExtension=${participant.filenameExtension}`
        );

        updatedParticipants.push(
          makeNullBuildParticipant(
            participant,
            `unsupported filenameExtension=${participant.filenameExtension}`
          )
        );

        continue;
      }

      console.log(`Processing ${participant.id}`);
      console.log(`Download URL: ${participant.downloadUrl}`);
      console.log(`File extension from metadata: ${participant.filenameExtension}`);

      const loaded = await load23andMeFileCloud_unknwn(
        participant.downloadUrl,
        participant.id
      );

      const loadedExtension = String(
        loaded.filenameExtension || ""
      ).toLowerCase();

      // ZIP files should be extracted to TXT by the loader.
      // Therefore, the final loaded file should be txt.
      if (loadedExtension !== "txt") {
        skippedCount++;

        console.warn(
          `Skipping ${participant.id}: downloaded unsupported file=${loaded.filename}, extension=${loaded.filenameExtension}`
        );

        updatedParticipants.push(
          makeNullBuildParticipant(
            participant,
            `downloaded unsupported file=${loaded.filename}, extension=${loaded.filenameExtension}`
          )
        );

        continue;
      }

      const dataToSave = getDataToSave(loaded);

      if (!dataToSave) {
        throw new Error("Downloaded TXT is empty or unsupported");
      }

      if (typeof dataToSave === "string" && !dataToSave.trim()) {
        throw new Error("Downloaded TXT is empty");
      }

      if (Buffer.isBuffer(dataToSave) && dataToSave.length === 0) {
        throw new Error("Downloaded TXT buffer is empty");
      }

      // For ZIPs, loaded.filename is the extracted inner .txt name.
      // For direct .txt files, it's the original filename.
      // Save under <id>_<filename>
      const savedFilename = makeSavedFilename(participant.id, loaded.filename);

      const outputPath = `geneticFiles/${savedFilename}`;

      await bucket.file(outputPath).save(dataToSave, {
        contentType: "text/plain"
      });

      const sizeMB = getSizeMB(dataToSave);

      updatedParticipants.push({
        ...participant,
        innerFilename: loaded.innerFilename || participant.innerFilename || null,
        valid23File: loaded.valid23File,
        matchedLineValid23File: loaded.matchedLineValid23File,
        genomeBuild: loaded.genomeBuild,
        genomeBuildFiles: [
          {
            downloadUrl: participant.downloadUrl || null,
            filename: loaded.filename || null,
            gcsPath: outputPath,
            gcsfilename: savedFilename,
            sizeMB,
            matchedLine: loaded.matchedLineGenomeBuild
          }
        ]
      });

      savedCount++;

      console.log(`Saved ${savedCount}: gs://${BUCKET_NAME}/${outputPath}`);
      console.log({
        id: participant.id,
        genomeBuild: loaded.genomeBuild,
        matchedLine: loaded.matchedLineGenomeBuild
      });
    } catch (err) {
      failedCount++;

      console.error(`FAILED ${participant?.id}: ${err.message}`);

      updatedParticipants.push({
        ...participant,
        valid23File: false,
        matchedLineValid23File: null,
        genomeBuild: null,
        genomeBuildFiles: [],
        processingNote: `FAILED: ${err.message}`
      });
    }
  }

  const updatedParticipantOutputPath =
    `updatedParticipantsList/participants_${LIMIT}_with_build.json`;

  await bucket.file(updatedParticipantOutputPath).save(
    JSON.stringify(updatedParticipants, null, 2),
    {
      contentType: "application/json"
    }
  );

  console.log(
    `Saved updated participant JSON to gs://${BUCKET_NAME}/${updatedParticipantOutputPath}`
  );

  const reportOutputPath = `runReports/import_report_${LIMIT}_${Date.now()}.json`;

  const report = {
    requested: LIMIT,
    found: participants.length,
    saved: savedCount,
    failed: failedCount,
    skipped: skippedCount,
    rawParticipantJson: participantOutputPath,
    updatedParticipantJson: updatedParticipantOutputPath
  };

  await bucket.file(reportOutputPath).save(
    JSON.stringify(report, null, 2),
    {
      contentType: "application/json"
    }
  );

  console.log(`Saved report to gs://${BUCKET_NAME}/${reportOutputPath}`);

  console.log("Import complete.");
  console.log(report);
}

main().catch(err => {
  console.error("FATAL ERROR:");
  console.error(err);
  process.exit(1);
});